version: '3.9'
services:
  db:
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - db_weather_data:/var/lib/postgresql/data
    networks:
      - weather_network
    
  redis:
    image: redis:latest
    networks:
      - weather_network
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/api
    depends_on:
      - redis
      - db
    env_file:
      - ./.env
    networks:
      - weather_network
    command: ["python", "run.py"]

volumes:
  db_weather_data:

networks:
  weather_network: