version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=weather_db
    volumes:
      - db_weather_data:/var/lib/postgresql/data
    networks:
      - weather_network
  
  redis:
    image: redis:latest
    networks:
      - weather_network
    volumes:
      - redis_data:/data

  web:
    image: rafaelrodriguess/weather-api
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
    env_file:
      - ./.env
    networks:
      - weather_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - weather_network
    depends_on:
      - web

volumes:
  db_weather_data:
  redis_data:

networks:
  weather_network:
    driver: overlay
    attachable: true
