"""empty message

Revision ID: 4e4bb378dcb9
Revises: a8b3b87b7a3f
Create Date: 2025-07-02 19:02:43.409686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4bb378dcb9'
down_revision = 'a8b3b87b7a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_weather_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.drop_constraint('fk_weather_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('generated_at')

    # ### end Alembic commands ###
